CREATE DATABASE IF NOT EXISTS office_crm;
USE office_crm;

CREATE TABLE IF NOT EXISTS campaign_uploads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  row_data JSON NOT NULL,
  module VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);